ChineseAddress/Areas/User/Controllers/PaymentController.cs
using _ChineseAddress.com.Areas.User.IServices;
using _ChineseAddress.com.Areas.User.Models;
using _ChineseAddress.com.Areas.User.Services;
using _ChineseAddress.com.Models;
using _ChineseAddress.com.Repository;
using PagedList;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace _ChineseAddress.com.Areas.User.Controllers
{
    [Authorize(Roles = "User")]
    [CustomActionFilter]
    public class PaymentController : Controller
    {
        private ISettingService<tblAddressBook, tblCustomer, tblCreditCard, tblPlan, PlansOptionModel, tblRewardPoint, ViewCustomerPaymentModel, tblCreditCardViewModel, tblCustomerPlanLinking> _repositorySetting;
        private IPaymentService<UserPaymentModel, ViewModelOrderinfo> _repository;

        public PaymentController(IPaymentService<UserPaymentModel, ViewModelOrderinfo> repo, SettingService repoSetting)
        {
            _repository = repo;
            _repositorySetting = repoSetting;
        }

        // GET: Payment
        // [Route("user/Payment")]
        [HttpGet]
        public ActionResult Index(string id, string type)
        {
            try
            {
                if (!string.IsNullOrEmpty(id))
                {
                    ViewBag.order_id = id;
                    TempData["PaymentOrerId"] = Cryptography.Decrypt(id);
                }
                if (type != null)
                {
                    TempData["PaymentOf"] = type;
                }
                //get Credit Cards Detail
                int orderId = Convert.ToInt32(TempData["PaymentOrerId"]);
                TempData.Keep("PaymentOrerId");

                ViewModelOrderinfo objViewModelOrderinfo = _repository.GetOrderDetail(orderId);
                List<tblCreditCardViewModel> tblcreditcards = _repositorySetting.GetCreaditCards();
                return View(Tuple.Create(tblcreditcards, objViewModelOrderinfo));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string CreditCardId)
        {
            try
            {
                int CardId = 0;
                int orderId = 0;
                string type = "";
                if (TempData["PaymentOrerId"] != null)
                {
                    TempData.Keep("PaymentOrerId");
                    ViewBag.order_id = Cryptography.Encrypt(Convert.ToString(TempData["PaymentOrerId"]));
                    TempData.Keep("PaymentOrerId");
                    orderId = Convert.ToInt32(TempData["PaymentOrerId"]);
                    TempData.Keep("PaymentOrerId");
                }
                if (TempData["PaymentOf"] != null)
                {
                    type = Convert.ToString(TempData["PaymentOf"]);
                    TempData.Keep("PaymentOf");
                }
                else
                {
                    ViewBag.Message = "showMessage('Error occured while processing your request.',false)";
                }
                if (!string.IsNullOrEmpty(CreditCardId))
                {
                    CardId = Convert.ToInt32(Cryptography.Decrypt(CreditCardId));
                    ViewBag.Message = _repository.ProcessPayment(orderId, CardId, type);
                    if (_repository._isSuccess)
                    {
                        TempData["successPayment"] = ViewBag.Message;
                        return RedirectToAction("OrderDetails", "Order");
                    }
                }
                else
                {
                    ViewBag.Message = "showMessage('Error occured while processing your request.',false)";
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            List<tblCreditCardViewModel> tblcreditcards = _repositorySetting.GetCreaditCards();
            return View(tblcreditcards);
        }

        [HttpGet]
        public ActionResult PaymentHistory(int? pageNumber)
        {
            try
            {
                IPagedList<UserPaymentModel> CustomerPayments = _repository.GetCustomerPayment(pageNumber ?? 1);
                return View(CustomerPayments);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult PaymentPlanUpgrade(string id, int? creditCardId, int pageNumber = 1)
        {
            int PlanId = 0;
            if (!string.IsNullOrEmpty(id))
            {
                ViewBag.PlanId = id;
                PlanId = Convert.ToInt32(Cryptography.Decrypt(id));
            }
            if (Request.RequestType.ToLower() != "get")
            {
                string msg = _repository.ProcessUpgradePlanPayment(PlanId, creditCardId ?? 0);
                ViewBag.Message = msg;
            }

            List<tblCreditCardViewModel> tblcreditcards = _repositorySetting.GetCreaditCards();
            return View(tblcreditcards);
        }
    }
}

ChineseAddress/Areas/User/Views/Payment/Index.cshtml
@model Tuple<List<_ChineseAddress.com.Areas.User.Models.tblCreditCardViewModel>, _ChineseAddress.com.Areas.User.Models.ViewModelOrderinfo>
@{
    ViewBag.Title = "ChineseAddress - Payment";
}
<section class="margintop90PX margintop90PX-xs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="~/DashBoard">Home</a></li>
                    <li><a href="~/Orders">Orders Detail</a></li>
                    <li class="active">Choose Payment Method</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@using (Html.BeginForm("Index", "Payment"))
{
    <section>
        <div class="container">
            <div class="box-grey">
                <div class="row">
                    <div class="col-sm-2 border-rgt space-top-bot paddingleft30PX force-center">
                        Ordered On:<br>
                        <strong>@(Model.Item2.orderon == null ? "" : Model.Item2.orderon.Value.ToString("yyyy/MM/dd"))</strong>
                    </div>
                    <div class="col-sm-2 border-rgt space-top-bot force-center">
                        Order Number:<br>
                        <strong>@Model.Item2.orderno</strong>
                    </div>
                    <div class="col-sm-2 border-rgt space-top-bot force-center">
                        Shipping Method:<br>
                        <strong>@Model.Item2.shipmethod</strong>
                    </div>
                    <div class="col-sm-2 border-rgt space-top-bot force-center">
                        Payable Amount:<br>
                        <strong>@Model.Item2.totalamount.ToString("F")</strong>
                    </div>
                    <div class="col-sm-2 border-rgt space-top-bot force-center">
                        Your Wallet Balance:<br>
                        <strong>@Model.Item2.WalletBalance.ToString("F")</strong>
                    </div>
                    <div class="col-sm-2 space-top-bot force-center">
                        Status:<br>
                        @{
                            clsCommon objclscomman = new clsCommon();
                            var Status = objclscomman.OrderStatus(Convert.ToString(Model.Item2.status));
                            if (Status != "0")
                            {
                                string[] SplitlabelCalss = Status.Split(',');
                                <span class="label @SplitlabelCalss[0]">@SplitlabelCalss[1]</span>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>

        <div class="container" id="container">
            <div class="row">
                <div class="col-sm-12"><h1>Choose Payment Method</h1><br /></div>
                <div class="col-sm-12">
                    <div role="tabpanel" class="tab-pane active" id="ready">

                        @Html.AntiForgeryToken()
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>

                                        <th>Card Type</th>
                                        <th>Name </th>
                                        <th>Card Number</th>
                                        <th>Expiry Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model == null || !Model.Item1.Any())
                                    {
                                        <tr>
                                            <td colspan="8" class="text-center">
                                                <h2><i class="fa fa-exclamation-circle"></i> No results found</h2>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        foreach (var item in Model.Item1)
                                        {
                                            <tr>
                                                <td>
                                                    @item.card_type
                                                </td>
                                                <td>
                                                    @item.Name
                                                </td>
                                                <td>
                                                    @if (item.is_default == true)
                                                    {
                                                        @("****" + item.card_num.ToString() + " (Default)")
                                                    }
                                                    else
                                                    {@("****" + item.card_num.ToString())}
                                                </td>
                                                <td>@item.card_expiry</td>
                                                <td>
                                                    <input type="submit" value="Pay Now" onclick="CreaditCard(this)" class="btn btn-success btn-xs" style="font-size: 12px !important;" />
                                                    <input type="hidden" name="CreditCardId" value="@_ChineseAddress.com.Models.Cryptography.Encrypt(Convert.ToString(item.Id))" />
                                                </td>
                                            </tr>

                                        }
                                    }
                                </tbody>
                            </table>
                          
                        </div>
                        @*<div class="row">
                            <div class="col-sm-12">
                                <span class="checkbox">
                                    <label style="font-size: 1em">
                                        <input value="false" id="Terms" name="Terms" unchecked type="checkbox">
                                        <span class="cr"><i class="cr-icon fa fa-check"></i></span>
                                        <label for="Terms"><a href="~/TermsAndConditions" target="_blank" class="btn btn-link checkbox-anchor">Terms & Conditions</a> and <a href="~/CancelReturnPolicies" target="_blank" class="btn btn-link checkbox-anchor">Cancellation and Return Policies</a> I have read, understood and agree to 4inShip</label>
                                    </label>
                                </span>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 form-group"><a href="~/CreditCards" class="btn btn-danger"><i class="fa fa-long-arrow-left"></i> Cancel </a></div>
                            </div>
                        </div>*@
                        <div class="row">
                            <div class="col-sm-12">
                                <a href="~/SingleCreditCard" class="btn btn-success btn-block"><i class="fa fa-plus"></i> Add New Credit Card</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
                                }
@section Scripts{
    <script type="text/javascript">
        $('#Terms').click(function () {
            if ($("#Terms").next('span').children().hasClass('fa-check') == true) {
                $('#Terms').prop('checked', false);
                $("#Terms").next('span').children().removeClass('fa-check')
                $("#Terms").val(false);
            }
            else if ($("#Terms").next('span').children().hasClass('fa-check') == false) {
                $('#Terms').prop('checked', true);
                $("#Terms").next('span').children().addClass('fa-check')
                $("#Terms").val(true);
            }
        });
    </script>
    <script type="text/javascript">
        function CreaditCard(item)
        {
            var value = $(item).next().val();
            $('input[name="CreditCardId"]').val(value);
        }
    </script>
    
    }

ChineseAddress/Areas/User/Views/Payment/PaymentHistory.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<_ChineseAddress.com.Areas.User.Models.UserPaymentModel>
@{
    ViewBag.Title = "PaymentHistory";
}
@{clsCommonServiceRoot objCommonServiceRoot = new clsCommonServiceRoot(); }
@using _ChineseAddress.com.Areas.Admin.Models
@using _ChineseAddress.com.Common.Services;
<section class="margintop90PX margintop90PX-xs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="~/DashBoard">Home</a></li>
                    <li class="active">Payment History</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<!-- body content start -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-12"><h1>Payment History</h1></div>
            <div class="col-sm-12">
                <div role="tabpanel" class="tab-pane active" id="ready">
                    <div class="table-responsive margintop15PX">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Invoice Number</th>
                                    <th>Order Number</th>
                                    <th>Method</th>
                                    <th>Type</th>
                                    <th>Amount</th>
                                    <th>Status</th>
                                    <th>Download</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (!Model.Any())
                                {
                                    <tr>
                                        <td colspan="5" class="text-center">
                                            <h2><i class="fa fa-exclamation-circle"></i> No results found</h2>
                                        </td>
                                    </tr>
                                }
                                else
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td><span>@(item.PaymentDate == null ? "" : item.PaymentDate.Value.ToString("yyyy/MM/dd"))</span></td>
                                            <td>@CheckIsNullorEmpty(item.InvNo)</td>
                                            @{string OrderID = _ChineseAddress.com.Models.Cryptography.Encrypt(Convert.ToString(item.OrderId));}
                                            @{int OrderRefernce;
                                                bool isNumeric = int.TryParse(item.OrderReferenceNumber, out OrderRefernce);
                                            }
                                            @if (isNumeric == true)
                                            {
                                                <td><a href="~/Orderinformation/@OrderID"> @item.OrderReferenceNumber</a></td>
                                            }
                                            else
                                            {
                                                <td>@CheckIsNullorEmpty(item.PlanType)</td>
                                            }
                                            @if (item.OrderReferenceNumber == "Direct-Single-Shipment")
                                            {
                                                <td>@("-----")</td>
                                            }
                                            else
                                            {
                                                <td>@item.Method</td>
                                            }

                                            <td>@item.InvoiceType</td>
                                            <td>@String.Format("${0:0.00}", item.Amount)</td>
                                            <td>@(Html.Raw(objCommonServiceRoot.GetInvoicePaidStatusLabel(item.Status)))</td>
                                            @if (item.InvoiceType == "order")
                                            {
                                                string OrderInvoice = item.OrderReferenceNumber + "_Invoice.pdf";
                                                <td>
                                                    <a class="btn btn-warning btn-xs" id="confirm" href="/CommonChild/DownloadInvoice/@item.OrderId" download="@OrderInvoice"><i class="fa fa-tag"> Invoice</i></a>
                                                </td>
                                            }
                                            else if (item.InvoiceType.ToLower() == "signup")
                                            {
                                                <td>
                                                    <a class="btn btn-warning btn-xs" id="confirm" href="/CommonChild/DownloadSignUpInvoice/@(Convert.ToString(item.InvNo+','+item.FK_Customer_Id))" download="SignUpInvoice.pdf"><i class="fa fa-tag">Invoice</i></a>
                                                </td>
											}
											else if (item.InvoiceType.ToLower() == "return shipment")
											{
												<td>
													<a class="btn btn-warning btn-xs" id="confirm" href="/CommonChild/DownloadReturnShipmentInvoice/@(Convert.ToString(item.InvNo+','+item.FK_Customer_Id))" download="ReturnShipmentInvoice.pdf"><i class="fa fa-tag">Invoice</i></a>
												</td>
											}
											else if (item.InvoiceType.ToLower() == "topup")
											{
												if (string.IsNullOrEmpty(item.InvNo))
												{
                                                    <td>@("-----")</td>
                                                }
                                                else
                                                {
                                                <td>
                                                    <a class="btn btn-warning btn-xs" id="confirm" href="/CommonChild/DownloadTopUpInvoice/@(Convert.ToString(item.FK_Customer_Id + "," + item.InvNo))" download="TopUp_Invoice.pdf"><i class="fa fa-tag">Invoice</i></a>
                                                </td>}
                                            }
                                        </tr>
                                                    }
                                                }
                            </tbody>
                        </table>
                    </div>
                    @Html.PagedListPager(Model, pageNumber => Url.RouteUrl("PaymentHistory", new { pageNumber = pageNumber }))
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script type="text/javascript">
        $(window).load(function () {
            @Html.Raw(TempData["OrderMessage"]);
            $("#datatablorder").DataTable({
                responsive: true,
                "order": [],
                columnDefs: [
                         { responsivePriority: 1, targets: 0 },
                         { responsivePriority: 2, targets: -1 }
                ]
            });

        });
    </script>
}

@helper CheckIsNullorEmpty(string str)
{
if (string.IsNullOrEmpty(str))
{
        @("-----")
}
else
{
        @(str)
}
}

ChineseAddress/Areas/User/Views/Payment/PaymentPlanUpgrade.cshtml
@model List<_ChineseAddress.com.Areas.User.Models.tblCreditCardViewModel>
@{
    ViewBag.Title = "Upgrade Plan Payment";
}

<section class="margintop90PX margintop90PX-xs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="~/DashBoard">Home</a></li>
                    <li><a href="~/Upgrade">Upgrade Your Plan</a></li>
                    <li class="active">Choose Payment Method</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section>

    <div class="container" id="container">
        <div class="row">
            <div class="col-sm-12"><h1>Choose Payment Method</h1><br /></div>
            <div class="col-sm-12">
                <div role="tabpanel" class="tab-pane active" id="ready">
                    @using (Ajax.BeginForm("PaymentPlanUpgrade", new AjaxOptions() { HttpMethod = "POST" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>

                                        <th>Card Type</th>
                                        <th>Name </th>
                                        <th>Card Number</th>
                                        <th>Expiry Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model == null || !Model.Any())
                                    {
                                        <tr>
                                            <td colspan="8" class="text-center">
                                                <h2><i class="fa fa-exclamation-circle"></i> No results found</h2>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @item.card_type
                                                </td>
                                                <td>
                                                    @item.Name
                                                </td>
                                                <td>
                                                    @if (item.is_default == true)
                                                    {
                                                        @("****" + item.card_num.ToString() + " (Default)")
                                                    }
                                                    else
                                                    {@("****" + item.card_num.ToString())}
                                                </td>
                                                <td>@item.card_expiry</td>
                                                <td>
                                                    <input type="submit" value="Pay Now" onclick="updateCreditCardId('@item.Id')" class="btn btn-success btn-xs" style="font-size: 12px !important;" />
                                                </td>
                                            </tr>

                                        }
                                    }
                                </tbody>
                            </table>
                            <input type="hidden" name="CreditCardId" id="CreditCardId" value="" />
                            <input type="hidden" name="id" value="@ViewBag.PlanId" />
                        </div>
                    }
                    <div class="row">
                        <div class="col-sm-12">
                            <a href="~/SingleCreditCard" class="btn btn-success btn-block"><i class="fa fa-plus"></i> Add New Credit Card</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script type="text/javascript">
        function updateCreditCardId(CreditCardId) {
            $("#CreditCardId").val(CreditCardId);
        }
    </script>
}