ChineseAddress/Areas/Admin/Controllers/CouponController.cs
using _ChineseAddress.com.Areas.Admin.Services;
using _ChineseAddress.com.Repository;
using _ChineseAddress.com.Services;
using System;
using System.Web.Mvc;

namespace _ChineseAddress.com.Areas.Admin.Controllers
{
    [CustomAuthorize(Url = "~/admin/login", Roles = "Admin")]
    public class CouponController : Controller
    {
        private CouponService objCouponService;

        public CouponController()
        {
            objCouponService = new CouponService();
        }

        // GET: Admin/Coupon
        [HttpGet]
        public ActionResult Index(int? id)
        {
            tblCoupon objCouponDetail = new tblCoupon();
            if (id != null)
            {
                TempData["Coupon_Id"] = id;
                objCouponDetail = objCouponService.getCouponById(id ?? 0);
            }
            else
            {
                if (TempData["Coupon_Id"] != null)
                {
                    TempData["Coupon_Id"] = null;
                }
            }
            BindCountries();

            return View(objCouponDetail);
        }

        [HttpPost]
        public ActionResult Index(tblCoupon objCoupon)
        {
            if (TempData["Coupon_Id"] != null)
            {
                objCoupon.id = Convert.ToInt32(TempData["Coupon_Id"]);
            }
            if (objCoupon.coupon_status != "")
            {
                objCoupon.status = Convert.ToInt16(objCoupon.coupon_status);
            }

            ViewBag.Message = objCouponService.AddUpdateCoupon(objCoupon);

            BindCountries();
            return View(objCoupon);
        }

        [OutputCache(Duration = 216000)]
        private void BindCountries()
        {
            try
            {
                ViewBag.country_to = (new CountryServices()).Country();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult ManageCoupon()
        {
            try
            {
                return View(objCouponService.GetCouponDetails());
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult IsCouponExist(string coupon_code, int? id)
        {
            bool isExist = objCouponService.IsCouponExist(coupon_code, (id ?? 0));
            return Json(!isExist, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult validateMinMaxOrder(double max_order_value, double min_order_value)
        {
            bool isExist = false;
            if (min_order_value <= max_order_value)
                isExist = true;
            return Json(isExist, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult validateStartEndDate(DateTime start_date, DateTime end_date)
        {
            bool isValid = false;
            if (start_date <= end_date)
                isValid = true;
            return Json(isValid, JsonRequestBehavior.AllowGet);
        }
    }
}

ChineseAddress/Areas/Admin/Views/Coupon/Index.cshtml
@model _ChineseAddress.com.Repository.tblCoupon

@{
    ViewBag.Title = "Admin";
}
<div class="content">
    <div class="box box-info">
        <div class="form-horizontal">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Customer Plan</h3>
                    <a href='@Url.Action("ManageCoupon")' class="btn btn-xs btn-primary pull-right"><i class="fa fa-eye" aria-hidden="true"> View All Coupons</i></a>
                </div>
                @using (Html.BeginForm("Index", "Coupon", FormMethod.Post))
                {
                    <div id="parent-container">
                        <div class="form-horizontal" id="child-container">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="code" class="col-sm-2 control-label">Coupon Code</label>
                                    <div class="col-sm-10">
                                        @Html.TextBoxFor(model => model.coupon_code, new { @class = "form-control", placeholder = "Coupon Code", @maxlength = "9" })
                                        @Html.ValidationMessageFor(model => model.coupon_code, null, new { @class = "error" })
                                        @Html.HiddenFor(model => model.id)
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" class="col-sm-2 control-label">Coupon Type</label>
                                    <div class="col-sm-10">
                                        <label>@Html.CheckBox("reccuring", (Model.reccuring ?? false), new { @class = "flat-red", @id = "rdlRecurring" })&nbsp;Recurring</label>
                                        &nbsp;
                                        <label>@Html.CheckBox("uniq_per_user", (Model.uniq_per_user ?? false), new { @class = "flat-red", @id = "rdlUniquePerUser" })&nbsp;Unique Per User</label>
                                        &nbsp;
                                        <label>@Html.CheckBox("new_users_only", (Model.new_users_only ?? false), new { @class = "flat-red", @id = "rdlNewUser" })&nbsp;New User Only</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" class="col-sm-2 control-label">Charge Type</label>
                                    <div class="col-sm-10">
                                        <label>@Html.RadioButton("rdlChargeType", true, ((Model.coupon_type ?? true) == true ? true : false), new { @class = "flat-red", @id = "rdlChargeTypeValue" })&nbsp;Value</label>
                                        &nbsp;
                                        <label>@Html.RadioButton("rdlChargeType", false, ((Model.coupon_type ?? true) == false ? true : false), new { @class = "flat-red", @id = "rdlChargeTypePercentage" })&nbsp;Percentage</label>
                                        @Html.HiddenFor(X => X.coupon_type)
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="value" class="col-sm-2 control-label">Coupon Value/Percentage</label>
                                    <div class="col-sm-10">
                                        @Html.TextBoxFor(model => model.coupon_value, new { @class = "form-control", placeholder = "Coupon Value/Percentage", type = "number", @min = "0.01", @step = "0.01" })
                                        @Html.ValidationMessageFor(model => model.coupon_value, null, new { @class = "error" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="min_order_value" class="col-sm-2 control-label">Order Min. Value</label>
                                    <div class="col-sm-10">
                                        @Html.TextBoxFor(model => model.min_order_value, new { @class = "form-control", placeholder = "Order Minimum Value", type = "number", @min = "0.01", @step = "0.01" })
                                        @Html.ValidationMessageFor(model => model.min_order_value, null, new { @class = "error" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="max_order_value" class="col-sm-2 control-label">Order Max. Value</label>
                                    <div class="col-sm-10">
                                        @Html.TextBoxFor(model => model.max_order_value, new { @class = "form-control", placeholder = "Order Maximum Value", type = "number", @min = "0.01", @step = "0.01" })
                                        @Html.ValidationMessageFor(model => model.max_order_value, null, new { @class = "error" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="start_date" class="col-sm-2 control-label">Start Date</label>
                                    <div class="col-sm-10">
                                        @Html.TextBoxFor(model => model.start_date, new { @class = "form-control textboxfor", @placeholder = "Start Date", @calendar = "enabledDates" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="end_date" class="col-sm-2 control-label">End Date</label>
                                    <div class="col-sm-10">
                                        @Html.TextBoxFor(model => model.end_date, new { @class = "form-control textboxfor", placeholder = "End Date", @calendar = "enabledDates" })
                                        @Html.ValidationMessageFor(model => model.end_date)
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="country_to" class="col-sm-2 control-label">Country To</label>
                                    <div class="col-sm-10">
                                        @Html.DropDownList("country_to", ViewBag.country_to as IEnumerable<SelectListItem>, new { @class = "form-control ", @SearchSelect = "true", @name = "country_to" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" class="col-sm-2 control-label">Coupon Status</label>
                                    <div class="col-sm-10">
                                        <label>@Html.RadioButton("rdlstatus", "0", false, new { @class = "flat-red", @id = "rdlstatus" })&nbsp;InActive</label>
                                        &nbsp;
                                        <label>@Html.RadioButton("rdlstatus", "1", true, new { @class = "flat-red", @id = "rdlstatus" })&nbsp;Active</label>
                                        &nbsp;
                                        <label>@Html.RadioButton("rdlstatus", "2", false, new { @class = "flat-red", @id = "rdlstatus" })&nbsp;Used</label>
                                        @Html.HiddenFor(model => model.coupon_status)
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="" class="col-sm-2 control-label">User Who Can Avail</label>
                                    <div class="col-sm-10">
                                        @Html.DropDownList("customer_id", (new _ChineseAddress.com.Areas.Admin.Services.CouponService().getAllCustomers()), "All Customers", new { @class = "form-control ", @SearchSelect = "true", @name = "customer_id" })
                                    </div>
                                </div>
                            </div>
                            <div class="box-footer" style="padding: 20px 221px;">
                                <input type="submit" class="btn btn-success pull-left" value="Submit" onclick="return SubmitClick()">
                                <a href='@Url.Action("Index")' class="btn btn-danger pull-left" style="margin:0 8px;">Cancel</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript" language="javascript">
        $(function () {
            @Html.Raw(ViewBag.Message)

            if ('@Model.country_to' != null) {
                $("#country_to").val('@Model.country_to');
                $("#country_to").trigger('change.select2');
            }
            if ('@Model.status' != null) {
                $(":radio[value=@Model.status]").trigger('click').iCheck('check');
            }
            if ($("#rdlChargeType:checked") == "False") {
                addMaxAttr();
            }
            $(document).on("ifChecked", "#rdlChargeTypePercentage", function () {
                addMaxAttr();
            });
            $(document).on("ifChecked", "#rdlChargeTypeValue", function () {
                removeMaxAttr();
            });
            $(document).on("ifUnchecked", "#rdlRecurring", function () {
                $("#rdlUniquePerUser").iCheck("uncheck");
            })
            /*Change min and max value of the Value column*/
            $(document).on("change", "input[id*=_order_value]", function () {
                if ($("input[name=rdlChargeType]:checked").val() === "True") {
                    removeMaxAttr();
                }
            });
        });
        function addMaxAttr() {
            $("#coupon_value").removeAttr("min").siblings('span').html('');
            $("#coupon_value").attr("max", "75");
        }
        function removeMaxAttr() {
            $("#coupon_value").siblings('span').html('');

            var min_odr_val = $("#min_order_value").val();
            var max_odr_val = $("#max_order_value").val();
            if (min_odr_val === "") {
                $("#coupon_value").removeAttr("min")
            }
            else {
               // $("#coupon_value").attr("min", min_odr_val);
            }
            if (max_odr_val === "") {
                $("#coupon_value").removeAttr("max")
            }
            else {
                $("#coupon_value").attr("max", max_odr_val);
            }
        }
        function SubmitClick() {
            if ($("form").valid()) {
                $("#coupon_status").val($("input[id=rdlstatus]:checked").val());
                $("#coupon_type").val($("input[name=rdlChargeType]:checked").val());
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}

ChineseAddress/Areas/Admin/Views/Coupon/ManageCoupon.cshtml
@model IEnumerable<_ChineseAddress.com.Repository.tblCoupon>
@{
    ViewBag.Title = "ManageCoupon";
}
<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Coupon Option</h3>
            <a href='@Url.Action("Index", "Coupon")' class="btn btn-xs btn-primary pull-right"><i class="fa fa-plus" aria-hidden="true"> Add Coupon Option</i></a>
        </div>
        <div class="form-horizontal">
            <div class="box-body">
                <table id="datatablemanagecoupon" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>

                            <th>Coupon Code</th>
                            <th>Coupon Type</th>
                            <th>Coupon Value</th>
                            <th>Min-Max Order Value</th>
                            <th>Recuring</th>
                            <th>New User Only</th>
                            <th>Unique Per User</th>
                            <th>Country To</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Status</th>
                            <th>Customer Name</th>
                            @*<th>Action</th>*@
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>

                                    <td>@item.coupon_code</td>
                                    <td>@((item.coupon_type==true)?"Value":"Percentage")</td>
                                    <td>@item.coupon_value</td>
                                    <td>@item.min_order_value - @item.max_order_value</td>
                                    <td>@item.reccuring</td>
                                    <td>@item.new_users_only</td>
                                    <td>@item.uniq_per_user</td>
                                    <td>@item.country_to</td>
                                    <td>@((item.start_date == null) ? "" : item.start_date.Value.ToString("yyyy/MM/dd"))</td>
                                    <td>@((item.end_date == null) ? "" : item.end_date.Value.ToString("yyyy/MM/dd"))</td>
                                    <td>
                                        @if (item.status == 0)
                                        {
                                            <label class="label label-danger">Inactive</label>
                                        }
                                        else if (item.status == 1)
                                        {
                                            <label class="label label-success">Active</label>
                                        }
                                        else
                                        {
                                            <label class="label label-warning">Used</label>
                                        }
                                    </td>
                                    <td>@item.customer_name</td>
                                    @*<td><a href="javascript:void(0)" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Edit Coupon"></i></a></td>*@
                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#datatablemanagecoupon").DataTable({
                responsive: true,
                "order": [],
                "columnDefs": [
                         { responsivePriority: 1, targets: 0 },
                         { responsivePriority: 2, targets: -1 }
                ]
            });
        });
    </script>
}