ChineseAddress/Areas/Admin/Controllers/PackagingOptionsController.cs
using _ChineseAddress.com.Areas.Admin.Services;
using _ChineseAddress.com.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace _ChineseAddress.com.Areas.Admin.Controllers
{
    [CustomAuthorize(Url = "~/admin/login", Roles = "Admin")]
    public class PackagingOptionsController : Controller
    {
        // GET: Admin/PackagingOptions
        private PackagingOptionsService Context = new PackagingOptionsService();

        public ActionResult Index(int? Id)
        {
            if (Id != 0)
            {
                return View(Context.GetblPackagingOptionsById(Id ?? 0).SingleOrDefault());
            }
            return View(new _ChineseAddress.com.Repository.tblPackagingOption());
        }

        public ActionResult InsertTblPackagingOptions()
        {
            return View("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult InsertTblPackagingOptions(tblPackagingOption tblpackagingoption, string Issignup, string Isshipment)
        {
            try
            {
                if (tblpackagingoption != null)
                {
                    ViewBag.Message = Context.InsertUpdatePackagingOptions(tblpackagingoption);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            tblPackagingOption roll = new tblPackagingOption();
            ModelState.Clear();
            return View("Index");
        }

        public ActionResult UpdateTblPackagingOptions(tblPackagingOption tblpackagingoption)
        {
            try
            {
                if (tblpackagingoption != null)
                {
                    ViewBag.Message = Context.InsertUpdatePackagingOptions(tblpackagingoption);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            tblPackagingOption roll = new tblPackagingOption();
            ModelState.Clear();
            return View("Index");
        }

        [HttpGet]
        public ActionResult PackagingOptions()
        {
            List<tblPackagingOption> lst = Context.GettblPackagingOptions().ToList();

            return View("GetPackagingOptionDetail", lst);
        }

        public JsonResult ChangeStatusPackagingOptionById(int Id)
        {
            if (Id != 0)
            {
                ViewBag.Message = Context.ChangeStatustblPackagingOptions(Id);
            }
            return Json(Id.ToString(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChangeSignupStatusPackagingOptionById(int Id)
        {
            if (Id != 0)
            {
                ViewBag.Message = Context.ChangeSignuptblPackagingOptions(Id);
            }
            return Json(Id.ToString(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChangeshipmentStatusPackagingOptionById(int Id)
        {
            if (Id != 0)
            {
                ViewBag.Message = Context.ChangeShipmentptblPackagingOptions(Id);
            }
            return Json(Id.ToString(), JsonRequestBehavior.AllowGet);
        }
    }
}

ChineseAddress/Areas/Admin/Views/PackagingOptions/GetPackagingOptionDetail.cshtml
@model List<_ChineseAddress.com.Repository.tblPackagingOption>
@{
    ViewBag.Title = "Admin";
}
<section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Packaging Option</h3>
            <a href='@Url.Action("Index", "PackagingOptions")' class="btn btn-xs btn-primary pull-right"><i class="fa fa-plus" aria-hidden="true"> Add Packaging Option</i></a>
        </div>
        <div class="form-horizontal">
            <div class="box-body">
                <table id="datatablepackagingoptions" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Visible On Signup</th>
                            <th>Visible On Shipment</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model == null)
                        {
                        }
                        else
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.title</td>
                                    <td>@item.description</td>
                                    @*<td><span>@(item.created_on == null ? "" : item.created_on.Value.ToString("yyyy/MM/dd"))</span></td>*@
                                    <td>
                                        <label class="textboxfor">
                                            <span title="Click here to Toggle this status" id='@("upspanStatus"+item.Id)' class="label @(item.is_signup == true ? "label-success" : "label-danger")">@(item.is_signup == true ? "True" : "False")</span>
                                        </label>
                                    </td>
                                    <td>
                                        <label class="textboxfor">
                                            <span title="Click here to Toggle this status" id='@("ntspanStatus"+item.Id)' class="label @(item.is_shipment == true ? "label-success" : "label-danger")">@(item.is_shipment == true ? "True" : "False")</span>
                                        </label>
                                    </td>
                                    <td>
                                        <label class="textboxfor">
                                            <span title="Click here to Toggle this status" id='@("spanStatus"+item.Id)' class="label @(item.status == true ? "label-success" : "label-danger")">@(item.status == true ? "Active" : "InActive")</span>
                                        </label>
                                    </td>
                                    <td style="padding: 14px 0px 0px 30px;">
                                        <a href="Index/@item.Id" class="btn btn-info btn-xs" title="Edit/View"><i class="fa fa-pencil"></i>@("/")<i class="fa fa-eye"></i></a>
                                        &nbsp;&nbsp;
                                        @*<a href="#" id='Delete @item.Id' onclick="DeleteDatas(@item.Id)" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"> Change Status</i></a>*@
                                    </td>
                                </tr>

                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            $("#datatablepackagingoptions").DataTable({
                responsive: true,
                "order": [],
                "columnDefs": [
                         { responsivePriority: 1, targets: 0 },
                         { responsivePriority: 2, targets: -1 }
                ]
            });
        });
        $('span[id^="spanStatus"]').click(function () {
            var statusid = $(this).attr('id');
            var id = statusid.replace('spanStatus', '');
            confirm('Are you sure,you want to change this status?', function (r) {
                if (r === true) {
                    $.ajax({
                        type: "post",
                        url: "/PackagingOptions/ChangeStatusPackagingOptionById",
                        data: { 'id': id },
                        success: function (id) {
                            showMessage("Status has been changed successfully", true)
                            if ($("#spanStatus" + id.toString()).text() === "Active")
                                $("#spanStatus" + id.toString()).text('InActive').toggleClass('label-success label-danger')
                            else
                                $("#spanStatus" + id.toString()).text('Active').toggleClass('label-success label-danger')
                        },
                        error: function (data) {
                            alert(data.x);
                            showMessage("", false)
                        }
                    });

                }
                else {
                    return false;
                }
            });

        });

        $('span[id^="upspanStatus"]').click(function () {
            var statusid = $(this).attr('id');
            var id = statusid.replace('upspanStatus', '');
            confirm('Are you sure you want to update packaging option?', function (r) {
                if (r === true) {
                    $.ajax({
                        type: "post",
                        url: "/PackagingOptions/ChangeSignupStatusPackagingOptionById",
                        data: { 'id': id },
                        success: function (id) {
                            showMessage("Packaging Option has been updated successfully", true)
                            if ($("#upspanStatus" + id.toString()).text() === "True")
                                $("#upspanStatus" + id.toString()).text('False').toggleClass('label-success label-danger')
                            else
                                $("#upspanStatus" + id.toString()).text('True').toggleClass('label-success label-danger')
                        },
                        error: function (data) {
                            alert(data.x);
                            showMessage("", false)
                        }

                    });

                }
                else {
                    return false;
                }
            });

        });
        $('span[id^="ntspanStatus"]').click(function () {
            var statusid = $(this).attr('id');
            var id = statusid.replace('ntspanStatus', '');
            confirm('Are you sure you want to update packaging option?', function (r) {
                if (r === true) {
                    $.ajax({
                        type: "post",
                        url: "/PackagingOptions/ChangeshipmentStatusPackagingOptionById",
                        data: { 'id': id },
                        success: function (id) {
                            showMessage("Packaging Option has been updated successfully", true)
                            if ($("#ntspanStatus" + id.toString()).text() === "True")
                                $("#ntspanStatus" + id.toString()).text('False').toggleClass('label-success label-danger')
                            else
                                $("#ntspanStatus" + id.toString()).text('True').toggleClass('label-success label-danger')
                        },
                        error: function (data) {
                            alert(data.x);
                            showMessage("", false)
                        }

                    });

                }
                else {
                    return false;
                }
            });

        });

        @Html.Raw(ViewBag.Message);
        function DeleteDatas(id) {
            var parent = $(this).parent().parent();
            $.ajax({
                type: "post",
                url: "/PackagingOptions/DeletePackagingOptionById",
                data: { 'id': id },
                success: function (id) {
                    if (id !== "0") {
                        $("a[id='Delete " + id + "']").eq(0).parent().parent().next('.child').remove();
                        $("a[id='Delete " + id + "']").eq(0).parent().parent().remove();
                        showMessage("Record has been deleted successfully", true);
                    }
                },
                error: function (data) {
                    alert(data.x);
                }
            });
        }
    </script>
}

ChineseAddress/Areas/Admin/Views/PackagingOptions/Index.cshtml
@model _ChineseAddress.com.Repository.tblPackagingOption
@{
    ViewBag.Title = "Admin";
}

<section class="content">
    @using (Html.BeginForm("InsertTblPackagingOptions", "PackagingOptions", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Add Packaging Option</h3>
                <a href='@Url.Action("PackagingOptions", "PackagingOptions")' class="btn btn-xs btn-primary pull-right"><i class="fa fa-eye" aria-hidden="true"> View All Packaging Options</i></a>
            </div>
            <div class="form-horizontal">
                <div class="box-body">

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
                        <div class="col-sm-10">
                            @Html.HiddenFor(m => m.Id)
                            @Html.TextBoxFor(m => m.title, new { @type = "text", @maxlength = "50", @class = "form-control textboxfor", id = "inputtitle", placeholder = "Title" })
                            @Html.ValidationMessageFor(m => m.title, null, new { @class = "error" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
                        <div class="col-sm-10">
                            @Html.TextAreaFor(m => m.description, new { @type = "text", @class = "form-control textboxfor", id = "inputdescription", placeholder = "Description" })
                            @Html.ValidationMessageFor(m => m.description, null, new { @class = "error" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputSignup" class="col-sm-2 control-label"> Visible On Signup</label>
                        <div class="col-sm-10" style="margin-top:5px">

                            <input value="true" class="flat-red" name="is_signup" type="checkbox" @((Model == null) ? "" : ((Model.is_signup ?? false) ? @"checked=""checked""" : ""))>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputShipment" class="col-sm-2 control-label">Visible On Shipment</label>
                        <div class="col-sm-10" style="margin-top:5px">
                            <input value="true" class="flat-red" name="is_shipment" type="checkbox" @((Model == null) ? "" : ((Model.is_shipment ?? false) ? @"checked=""checked""" : ""))>
                        </div>
                    </div>
                </div>
                <div class="box-footer" style="padding: 20px 221px;">
                    <button type="submit" id="SubmitData" class="btn btn-success">Submit</button>
                    <a href='@Url.Action("PackagingOptions", "PackagingOptions")' class="btn btn-danger">Cancel</a>
                </div>
            </div>
        </div>
    }
</section>
@section Scripts {
    <script type="text/javascript">
        @Html.Raw(ViewBag.Message);
        var JsonModel = '@Html.Raw(Json.Encode(@ViewBag.Message))';
        if (JsonModel === 'null') {
        } else if (JsonModel === '"showMessage(\u0027Updated successfully\u0027,true);"') {
            setTimeout(function() {
                window.location.pathname = '/Admin/PackagingOptions/PackagingOptions';
            }, 2000);};
    </script>

}

ChineseAddress/Areas/Admin/Views/PackagingOptions/UpdateTblPackagingOptions.cshtml
@{
    ViewBag.Title = "UpdateTblPackagingOptions";
}

<h2>UpdateTblPackagingOptions</h2>